### ISSUE TITLE
monitor label hardcoded

### ISSUE THREAD

**Issue by patagonaa** [zhyon404/prom2influx#2]
First of all, thank you for developing this useful tool, it saved me a lot of headache.

The only thing that didn't work right away when I used it to migrate my Prometheus was, that the monitor label wasn't right, which is why my queries didn't find any of the migrated data.

TL;DR:
in transfer.go the monitor label "codelab-monitor" is hardcoded, this should probably be set by a command line argument instead.

**Comment by zhyon404** [comment]
@patagonaa this is a good idea? would you like send a pr for this?

**Comment by patagonaa** [comment]
i could definitely try, but i haven't written a single line of go ever so it might be a good idea to let someone do it who knows what they are doing

**Comment by zhyon404** [comment]
@patagonaa add flag monitor-label
